### PR TITLE
Interop working from Xamarin to Blazor.  Need to refactor to make passing parameters cleaner

### PR DESCRIPTION
**Pull request by Daddoon**
Interop working from Xamarin to Blazor.  Need to refactor to make passing parameters cleaner

### CODE REVIEW

**Comment by Daddoon** [comment]
@vicjgg Merged your update in this branch. I will try to refactor this very soon, and do little modification.

I will add a test button in the InteropApp project, to forward a simulation of PostMessage events also.

**Comment by vicjgg** [comment]
Hi,
I submitted a PR.

Victor J. Gorri
973-800-0625
victor@ibeanzinc.com<mailto:victor@ibeanzinc.com>

**Comment by Daddoon** [comment]
I already merged your fork in the https://github.com/Daddoon/BlazorMobile/tree/dev_postmessage_update branch.

As i want to do a little review on your code this evening.
I will then merge this branch to the master and release a NuGet package update.

**Comment by Daddoon** [comment]
@vicjgg I have done changes in the https://github.com/Daddoon/BlazorMobile/tree/dev_postmessage_update branch.

This should be fine and ready to be released.
There is now two way of posting message:

- CallJSInvokableMethod on Webview (previously your PostMessage)
- PostMessage method on Webview

See some integration test code in the **BlazorMobile.InteropBlazorApp** project, in the **Counter** page.

I should write some documentation about this before releasing, and also migration documentation.
I will do this tomorrow i think, however feel free to test from this branch, or to PR accross-fork if you want to test it from your repo.

**Comment by vicjgg** [comment]
I’ll check it out.
Thanks again.


Victor J. Gorri
973-800-0625
victor@ibeanzinc.com<mailto:victor@ibeanzinc.com>

**Comment by Daddoon** [comment]
Actually there is a mistake i must fix tomorrow : When forwarding the
JSInvokable method in the BlazorToXamarin dispatcher class, i bubble the
parameters object[] in another object[] for the method invokation. Actually
i mimic-ed the PostMessage API parameter received behavior but this is
wrong.

I must remove the object[] bubbling when invoking, and also change the
JSInvokable test method signature to the expected parameters of course. Si
changing object[] to string parameter signature.

Btw the main advantage of the Message API otherwise, except the parameters
type hidding witch is less nice, is to easily being able to send message to
instanciated object. the invokable method will have more difficulties to
target rendered component at runtime without tricks.

**Comment by vicjgg** [comment]
I’ll take a look…

My needs (so far) have only been to send messages to pop modal screen/alerts/forms from location or push services…

Therefore it was pretty easy to just use a class with some static methods and use DI to inject the services.

Your way sounds much more robust.  I look forward to seeing it,

Victor J. Gorri
973-800-0625
victor@ibeanzinc.com<mailto:victor@ibeanzinc.com>

**Comment by Daddoon** [comment]
I fixed my code.
And also made a fundamental change in the PostMessage API.

I made it working with the same kind of logic and management you can find on the Xamarin.Forms Messaging API.

This mean instead:

- You can only post one parameter in PostMessage on the native side
- On the Blazor side, you instead register to a specific message name **with** a specific argument type expected. If a message is sent from native that does not match your message name and delegate expected argument type, it will be ignored, otherwise executed, and you will receive the expected parameter type in your Blazor app delegate, instead of the previous object[].

This also mean that you can post multiple messages with same names but not same delegate signature. As said previously, only matching argument type delegates will be fired.

I think it's a better implementation. Even if limiting to one argument, it's a lot less cryptic than sending object or object[] values, and prevent to always do casting or type check, from a usage point of view.

**Comment by vicjgg** [comment]
Hi,
I think one argument is fine. Typically sending a modeled class anyway.

Will download and try out today.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by Daddoon** [comment]
Thanks !

Of course i updated the interop app test page (counter) with theses changement in order to validate them.

You have one PostMessage expecting a string, and another expecting a boolean. Both with same message name.

Also, i'm merging theses update on my current BlazorMobile 3.0.11 dev branch. There is a lot of fix and improvements on the dev branch, and actually i would prefer to release everything at the same time.

There is an opt-in fix for iOS 13 crashing on the next release (as still waiting to Microsoft to release a new version of Blazor with the fix), consistent iframe navigation event handling on Android and more...If you are curious, you can check the github issues Milestone related to that.

**Comment by Daddoon** [comment]
Well actually my update does not work. I just tested, it does work when executing from a pure .Net core environment, like when i test from remote debugging, but not in the wasm implementation.

I suspect WASM not being able to honor the Delage.DynamicInvoke method.
Sorry to this new, i must find a workaround for the invokation in wasm mode

**Comment by vicjgg** [comment]
Yeah…
I tried A LOT of different things that didn’t work and could never get events/delegates to work.
Most of what I wrote was a work around, I’ll have a look over the weekend and see if I can help.

Victor J. Gorri
973-800-0625
victor@ibeanzinc.com<mailto:victor@ibeanzinc.com>

**Comment by Daddoon** [comment]
Actually i tested and it's more related about serialization issue when the root object to deserialize is a plain C# CLR object, when trying to fetch the expected type with my TypeProxy class.

.NET Core succeed, but WASM fail and seem to not even try to use the advanced binders that cover the .NET Core (using System.PrivateCoreLib) and Mono implementation (WASM) using the mscorlib namespace assembly.

**Comment by Daddoon** [comment]
Fixed it in my last commit on the branch.

I workarounded, as the CrossPlatformBinder is not called in this particular case, i forced to change assemblies name in the JSON if a previous deserialization call failed in the BridgeSerializer helper.

This seem to work fine!

**Comment by Daddoon** [comment]
I just finished today my last technical task, managing all the navigating
behaviors on ElectronNET to Xamarin.Forms driver, iframe / subframe
navigating included.

The current 3.0.11 branch is actually RTM , i just need to write the
documentation tomorrow or another day.

That mean you can upgrade to this branch or wait officials NuGet packages
to be shipped.

**Comment by Daddoon** [comment]
Well, actually done a last push.

I refactored some internal calls, that does not change any functionnality.
However i have made an enchancement about failure when interoping.

On previous version, if there was a JSON deserialization exception, the exception was thrown internally, but the calling Task was never notified about this exception, as it was at deserialization level before coming to the Task management system.

Now, if a task fail when deserializing on Blazor side (like if you have a type present on native Xamarin but not in Blazor), the code now try to fetch the TaskIdentity property from the failed deserialization, and forward the exception and inner exception to the original calling task.

This prevent JSON deserialization exceptions when interopping, to block the Task in Blazor eternally, as there is no CancellationToken system implemented yet too.

**Comment by Daddoon** [comment]
BlazorMobile 3.0.11 has been shipped on Nuget, and the documentation has been updated.
Thanks for your contribution!

**Comment by Daddoon** [comment]
Just for your info, i just added the [changelog here](https://github.com/Daddoon/BlazorMobile/releases/tag/3.0.11-preview9.19465.2)

**Pull request merged**
